### ISSUE TITLE
Not updating ark data

### ISSUE THREAD

**Issue by Hendrik83** [tsebring/ArkBot#12]
Hi, 

On my fresh windows 10 installation it does not auto update.
There is nothing in the logs.

Is it possible to trigger the update or am i missing something. I run the bot as administrator.

Thx.

**Comment by tsebring** [comment]
It auto updates when it detects a change to the save file path(s) that you have configured. I'm in the middle of rewriting the entire thing to support multiple servers, so the configuration have been changing quite a bit with every version.

In the latest version you have to configure the each server separately in addition to a temporary primary server (which is the configuration from before).

Use the defaultconfig.json as a template and make sure every path is valid.

**Comment by Hendrik83** [comment]
Failed to update server (server1)
[_serverUpdate(R:\ARK\ArkBot\ArkBot\Ark\ArkServerContext.cs:229)]

<Exception>
  <System.NullReferenceException>
    <Current />
    <Message>De objectverwijzing is niet op een exemplaar van een object ingesteld.</Message>
    <TargetSite>TPropertyValue GetPropertyValue[TPropertyValue](ArkSavegameToolkitNet.IPropertyContainer, ArkSavegameToolkitNet.Types.ArkName)</TargetSite>
    <Source>ArkSavegameToolkitNet</Source>
    <StackTrace><![CDATA[bij ArkSavegameToolkitNet.IPropertyContainerExtensions.GetPropertyValue[TPropertyValue](IPropertyContainer self, ArkName name) in C:\Repos\ArkSavegameToolkitNet\ArkSavegameToolkitNet\IPropertyContainerExtensions.cs:regel 48
bij ArkSavegameToolkitNet.Domain.ArkItem..ctor(IGameObject item, ISaveState saveState) in C:\Repos\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkItem.cs:regel 86
bij ArkBot.Ark.ArkServerContext.<>c__DisplayClass60_1.<_serverUpdate>b__19(GameObject x) in R:\ARK\ArkBot\ArkBot\Ark\ArkServerContext.cs:regel 213
bij System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
bij ArkBot.Ark.ArkServerContext._serverUpdate(Boolean manualUpdate, IConfig fullconfig, ISavegameBackupService savegameBackupService, IProgress`1 progress, CancellationToken ct) in R:\ARK\ArkBot\ArkBot\Ark\ArkServerContext.cs:regel 213]]></StackTrace>
  </System.NullReferenceException>
</Exception>

With the latest version

**Comment by tsebring** [comment]
The patch introduced changes to the save file format which should be fixed now. I think that might be the save update problem you were having.

Once in a while the update process will run into a file that is in use by the game server which may cause the update to fail. It is on a long list of things to improve.

It is not possible to set a manual update schedule. Better handling of failed updates (automatic retries) would be something nice to have in the future. Currently you can trigger a new update by running the admin command saveworld which is also available through the bot (!admin <serverkey> saveworld).

"Disconnected" is still a problem with Discord.Net that I cannot fix. When they release a stable version of 1.0 I will attempt to update to remedy the issue. Updating is their recommended approach and 0.9 is basically abandoned. There is simply nothing to be done right now. And the changes required to update to 1.0 will be a massive amount of work.

**Comment by Hendrik83** [comment]
It still does not auto update.
https://hastebin.com/kazolibeyu.rb

`Failed to update server (server1)
[_serverUpdate(R:\ARK\ArkBot\ArkBot\Ark\ArkServerContext.cs:231)]

<Exception>
  <System.NullReferenceException>
    <Current />
    <Message>De objectverwijzing is niet op een exemplaar van een object ingesteld.</Message>
    <TargetSite>TPropertyValue GetPropertyValue[TPropertyValue](ArkSavegameToolkitNet.IPropertyContainer, ArkSavegameToolkitNet.Types.ArkName)</TargetSite>
    <Source>ArkSavegameToolkitNet</Source>
    <StackTrace><![CDATA[bij ArkSavegameToolkitNet.IPropertyContainerExtensions.GetPropertyValue[TPropertyValue](IPropertyContainer self, ArkName name) in C:\Repos\ArkSavegameToolkitNet\ArkSavegameToolkitNet\IPropertyContainerExtensions.cs:regel 48
bij ArkSavegameToolkitNet.Domain.ArkItem..ctor(IGameObject item, ISaveState saveState) in C:\Repos\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkItem.cs:regel 86
bij ArkBot.Ark.ArkServerContext.<>c__DisplayClass64_1.<_serverUpdate>b__19(GameObject x) in R:\ARK\ArkBot\ArkBot\Ark\ArkServerContext.cs:regel 215
bij System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
bij ArkBot.Ark.ArkServerContext._serverUpdate(Boolean manualUpdate, IConfig fullconfig, ISavegameBackupService savegameBackupService, IProgress`1 progress, CancellationToken ct) in R:\ARK\ArkBot\ArkBot\Ark\ArkServerContext.cs:regel 215]]></StackTrace>
  </System.NullReferenceException>
</Exception>
![knipsel](https://cloud.githubusercontent.com/assets/60172/25862432/5455b6ee-34e8-11e7-9351-cd1624c13c79.PNG)
`

**Comment by tsebring** [comment]
Which ARK map is active on server1? Are you able to upload a copy of the .ark/.arkprofile/.arktribe files so that I can trace the error?

Latest version now has a menu option to manually trigger server updates.
![image](https://cloud.githubusercontent.com/assets/408350/25873850/4ecb3f0a-3510-11e7-81da-9fbb7ddc4b9b.png)

You are getting way more disconnects than I have ever seen. How many users are on the server?

**Comment by Hendrik83** [comment]
[Google Drive](https://drive.google.com/file/d/0B8VvDxvLcGrFcEk3R19CM204Z00/view?usp=drivesdk)
On the discord server? ~50 offline and online and ~20 online most of the time.

On one server i have the island and scorched map.
And another server for the center and both dont update.
[Config File](https://hastebin.com/idipuzunud.json)

Thx.

**Comment by tsebring** [comment]
I believe I was able to reproduce and fix the server update issue you are having in 6df9212c2971b66b585555ba64a793514124a962. Try the latest version and see if it helps.

The number of discord users is nothing out of the ordinary so I would expect fewer disconnects. The bug is very strange to begin with, let us hope the Discord.Net team will release a stable version of 1.0 soon. For some features, the web app can be an alternative (https://github.com/tsebring/ArkBot#web-app-under-development).

**Comment by Hendrik83** [comment]
Thanks.
Going to try it now.

**Comment by Hendrik83** [comment]
So i removed everything and build it from scratch.
The build was successful but did not include the Webapi folder so it failed to start the bot.
i took one from an earlier build.
Ark tools did not unpack and i had to do this manually.

It is now running a few hours and it only shows one disconnect. But it's still not auto updating.
With the manual triggers it works.

**Comment by tsebring** [comment]
You don't actually need to build it yourself unless you want to make changes.
This link is always built from the latest sources (open as zip-archive, binaries under /tools):
https://www.myget.org/F/tsebring/api/v2/package/ArkDiscordBot

One version yesterday had the problem with the /webapi folder, but the latest sources have that issue fixed.


Auto-update works by setting up a filesystem watcher in windows on the .ark files configured for each server instance (https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher(v=vs.110).aspx). For the .ark file to change the server have to save, so make sure autosave it setup or run the admin command "cheat saveworld".

You can test it out by copying a save over the one you have configured. If nothing happens then the watcher is not working. If you want you can start ArkBot it in the VS debugger and set breakpoints on /ArkBot/ArkSaveFileWatcher.cs (method: _watcher_Changed) and /ArkBot/Ark/ArkContextManager.cs (method: _saveFileWatcher_Changed). If those two do not trigger then it is a problem with the OS not reporting changes.

Manual trigger queues a new update regardless of the .ark file having changed or not. If no server saves are happening make sure AutoSavePeriodMinutes is set in [ServerSettings].

**Comment by Hendrik83** [comment]
Its ok i did it this way to try to help but im not that good.
I tried to trigger the update but it did not do it.

When searching info about the filesystemwatcher i saw its a bit unreliable when you have a lot of activity on your drive.

**Comment by tsebring** [comment]
Try the latest version with the config.json option `"useCompatibilityChangeWatcher":  true`. That should work for you.

**Comment by Hendrik83** [comment]
Yes! It works. 👍 
Now also the channel description gets updated but only shows one at the time and to fast.

![](https://imgurl.nl/i/H266-V2ZPc.gif)

**Comment by tsebring** [comment]
I'll add that to the list of bugs to fix.
